import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReduxProvider from '@/ReduxProvider';
import { Provider as JotaiProvider } from 'jotai';
import { Header } from '@/features/Header';
import { ThemeProvider } from '@/features/ThemeContext';
import { OrdersProvider } from "@/StateMachineProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* Скрипт для предотвращения мерцания темы */}
        <script dangerouslySetInnerHTML={{
          __html: `
            (function() {
              // 1. Проверяем сохраненную тему в localStorage
              const savedTheme = localStorage.getItem('theme');
              // 2. Проверяем системные предпочтения
              const systemPrefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
              // 3. Определяем начальную тему
              const initialTheme = savedTheme || (systemPrefersDark ? 'dark' : 'light');
              // 4. Применяем тему сразу, до загрузки React
              document.documentElement.classList.add(initialTheme);
              // 5. Сохраняем в data-атрибут для доступа из React
              document.documentElement.setAttribute('data-theme', initialTheme);
            })();
          `
        }} />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
          <JotaiProvider>
            <ThemeProvider>
              <OrdersProvider>
              <Header />
              <main className="">
                {children}
              </main>
              </OrdersProvider>
            </ThemeProvider>
          </JotaiProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
